# Referencias: https://github.com/wurstmeister/kafka-docker

version: '2.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200" 
      - "9300:9300"
    volumes:
      - data01:/usr/share/elasticsearch/data
  dito-producer:
    image: lcastrooliveira/dito-data-producer:0.0.1-SNAPSHOT
    environment:
      - KAFKA_ADVERTISED_HOST_NAME
    depends_on:
      - kafka
    ports:
      - "8080:8080"
  dito-consumer:
    image: lcastrooliveira/dito-data-consumer:0.0.1-SNAPSHOT
    environment:
      - KAFKA_ADVERTISED_HOST_NAME
    depends_on:
      - kafka
      - elastic
    ports:
      - "8081:8081"
  data-manipulation:
    image: lcastrooliveira/dito-data-manipulation:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
volumes:
  data01:
    driver: local
